# Generated by Django 6.0.7 on 2026-07-09 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stores.category')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('parent', 'name'), name='unique_category_name_per_parent')],
            },
        ),
    ]
